iliakan/javascript-nodejs

styles/blocks/code-tabs/code-tabs.styl
styles/blocks/prism/my-prism.styl

* добавил фон каждому числу в листинге
* добавил хитрожопую распорку на трехзначные числа

Отступы и фон под числами #146

---

handlers/profile/templates/partials/account.jade
handlers/tutorial/templates/tutorial.jade
styles/blocks/course-info/course-info.styl
styles/blocks/course-search/course-search.styl
styles/blocks/important/important.styl
styles/blocks/profile/profile.styl
styles/blocks/profile/profileProviders.styl

исправления по issues

---

styles/base.styl
styles/blocks/sitetoolbar/sitetoolbar.styl
styles/blocks/tutorial-progress/tutorial-progress.styl
templates/blocks/sitetoolbar.jade

на обычных страницах его нет и у шапки есть тень, в учебнике есть прогресс-бар

#277 прогресс-бар для учебника

---

handlers/profile/templates/partials/aboutme.jade
handlers/profile/templates/partials/account.jade
handlers/profile/templates/partials/profilePassword.jade
styles/blocks/profile/profile.styl
styles/blocks/profile/profileField.styl

внешний вид смены пароля в профиле

---

handlers/tutorial/templates/_map.jade
styles/blocks/tutorial-map-overlay/tutorial-map-overlay.styl
styles/blocks/tutorial-map/tutorial-map.styl

position: fixed фильтр в карте сайта

---

handlers/markup/templates/blocks/quiz-results-table.jade
handlers/markup/templates/pages/profile-quiz.jade
styles/blocks/quiz-result/quiz-result.styl
styles/blocks/quiz-results-indicator/quiz-results-indicator.styl
styles/blocks/quiz-results-table/quiz-results-table.styl

исправление индикатора, время теста в профиле

---

styles/blocks/comments/comments.styl
templates/blocks/comments.jade

попап с пояснениями для комментариев

---

styles/blocks/comments/comments.styl

гор. скролл на маленьком экране

---

handlers/auth/templates/forgot-form.jade
handlers/auth/templates/login-form.jade
handlers/auth/templates/register-form.jade
handlers/markup/templates/blocks/quiz-question.jade
handlers/markup/templates/pages/quiz-results.jade
handlers/markup/templates/pages/quiz.jade
styles/blocks/article-tablet-foot/article-tablet-foot.styl
styles/blocks/login-form/login-form.styl
styles/blocks/quiz-question/quiz-question.styl
styles/blocks/sitetoolbar/sitetoolbar.styl
templates/blocks/sitetoolbar.jade

Small fixes

---

handlers/markup/templates/blocks/page-footer.jade
handlers/markup/templates/blocks/quiz-question.jade
handlers/markup/templates/layouts/base.jade
handlers/markup/templates/pages/quiz-results.jade
handlers/markup/templates/pages/quiz.jade
styles/blocks/page-footer/page-footer.styl
styles/blocks/quiz-question/quiz-question.styl

футер и блоки для вариантов ответов тестов

---

handlers/markup/templates/blocks/quiz-question.jade
handlers/markup/templates/pages/quiz-results.jade
handlers/markup/templates/pages/quiz.jade
styles/blocks/banner-bottom/banner-bottom.styl
styles/blocks/course-info/course-info.styl
styles/blocks/important/important.styl
styles/blocks/lessons-list/lessons-list.styl
styles/blocks/page/page.styl
styles/blocks/quiz-question/quiz-question.styl

баннер и отступы на маленьких экранах

---

handlers/profileGuest/templates/aboutme.jade

#388 исправил шаблон вывдо строк в публичном профиле

---

styles/blocks/course-info/course-info.styl
styles/blocks/course-search/course-search.styl

Для телефонов убрать блок поиска на главной #426

---

styles/blocks/page-footer/page-footer.styl
styles/blocks/page-wrapper/page-wrapper.styl

footer на внутренних страницах (мобильная версия) #452

---

handlers/payments/common/templates/paypal-currency-form.jade
styles/blocks/login-form/login-form.styl
styles/blocks/modal/modal.styl
styles/blocks/paypal-currency-form/paypal-currency-form.styl
styles/index.styl

Выбор валюты в Paypal #447

---

handlers/markup/templates/blocks/register-form-contacts.jade
handlers/markup/templates/blocks/register-form-participants.jade
handlers/markup/templates/blocks/register-form-payment.jade
handlers/markup/templates/blocks/register-form-success.jade
handlers/markup/templates/pages/courses-register-contacts.jade
handlers/markup/templates/pages/courses-register-participants.jade
handlers/markup/templates/pages/courses-register-payment.jade
handlers/markup/templates/pages/courses-register-success.jade
styles/blocks/complex-form/complex-form.styl
styles/blocks/course-add-participants/course-add-participants.styl
styles/blocks/course-register-contacts/course-register-contacts.styl
styles/blocks/course-register-info/course-register-info.styl
styles/blocks/course-register-payment/course-register-payment.styl
styles/blocks/course-register-settings/course-register-settings.styl
styles/blocks/course-register-success/course-register-success.styl
styles/blocks/courses-register-common/courses-register-common.styl
styles/blocks/courses-register-participants/courses-register-participants.styl
styles/blocks/number-input/number-input.styl
styles/blocks/receipts/receipts.styl
styles/blocks/receipts/receipts_register.styl
styles/blocks/switch-input/switch-input.styl
styles/index.styl

#286 верстка

---

handlers/markup/templates/blocks/invoice-table.jade
handlers/markup/templates/pages/profile-invoice.jade
styles/blocks/button/button.styl
styles/blocks/full-phone/full-phone.styl
styles/blocks/input-select/input-select.styl
styles/blocks/invoice-table/invoice-table.styl
styles/blocks/payment-setting/payment-setting.styl
styles/index.styl

#286 вкладка "заказ"

---

handlers/markup/templates/blocks/payment-settings.jade
styles/blocks/course-search/course-search.styl
styles/blocks/payment-setting/payment-setting.styl
styles/blocks/sitetoolbar/sitetoolbar.styl
styles/blocks/tutorial-map-overlay/tutorial-map-overlay.styl
templates/blocks/sitetoolbar.jade

#464 поправил 1 и 2 пункт + мелочи еще

---

handlers/auth/templates/forgot-form.jade
handlers/auth/templates/forgot-recover.jade
handlers/auth/templates/register-form.jade
handlers/markup/templates/blocks/courses-table.jade
handlers/markup/templates/pages/profile-courses.jade
styles/blocks/courses-table/courses-table.styl
styles/blocks/profile/profile.styl
styles/index.styl

курсы в профиле и фикс кнопок

---

handlers/markup/templates/blocks/courses-features.jade
handlers/markup/templates/pages/courses-home.jade
handlers/quiz/client/index.js
handlers/quiz/templates/blocks/quiz-tablet-timeline.jade
handlers/quiz/templates/blocks/quiz.jade
styles/blocks/courses-features/courses-features.styl
styles/index.styl

тут еще затисалось начало верстки морды курсов, но оно ничего не сломает

timeline для мобильных в болевых шаблонах

---

styles/blocks/nodejs-screencast-header/nodejs-screencast-header.styl
styles/blocks/sitetoolbar/sitetoolbar.styl

hover share кнопок и закругдение юзерпика

---

handlers/markup/templates/pages/courses-feedback.jade
styles/blocks/course-feedback/course-feedback.styl
styles/blocks/rating-chooser/rating-chooser.styl
styles/index.styl

Форма для отзывов #570

---

styles/blocks/sitetoolbar/sitetoolbar.styl

Горизонтальная прокрутка в учебнике #600

---

handlers/courses/client/participantDetails/index.js
handlers/courses/templates/invite/askParticipantDetails.jade
handlers/markup/templates/pages/courses-feedback.jade
styles/blocks/complex-form/complex-form.styl
styles/blocks/course-feedback/course-feedback.styl
styles/blocks/courses-professionals/courses-professionals.styl
styles/blocks/main/main.styl
styles/blocks/participant-application/participant-application.styl
styles/blocks/upload-userpic/upload-userpic.styl
styles/blocks/variables/variables.styl
styles/index.styl

анкета учатника и мелочи

---

handlers/markup/templates/blocks/courses-materials-add.jade
handlers/markup/templates/blocks/courses-materials.jade
handlers/markup/templates/pages/courses-materials.jade
styles/blocks/courses-materials-add/courses-materials-add.styl
styles/blocks/courses-materials/courses-materials.styl
styles/blocks/task/task.styl
styles/blocks/variables/variables.styl
styles/index.styl

Цвет кнопки и раздел загрузки материалов

---

handlers/courses/templates/feedback/list.jade
handlers/markup/templates/pages/courses-feedback-many.jade
styles/blocks/course-feedback/course-feedback.styl
styles/blocks/feedback-stat/feedback-stat.styl
styles/blocks/pie/pie.styl
styles/blocks/profile/profileField.styl
styles/blocks/tutorial-map-overlay/tutorial-map-overlay.styl

много мелочей

---

handlers/markup/templates/pages/participants-profiles.jade
styles/blocks/participants-profiles/participants-profiles.styl
styles/blocks/questionnaire/questionnaire.styl
styles/ru.styl
templates/blocks/sitetoolbar-light.jade

* Курс: Анкеты участников #731 
* Нет прогресса в англ версии #751

Анкеты участников и тублар для анг версии

---

gulpfile.js

Cleaned up comments

---

handlers/markup/blocks/newsletter-form/index.jade
templates/blocks/text-input/index.jade

add error into text-input mixin

---

handlers/markup/blocks/newsletter-status/index.jade
handlers/markup/blocks/newsletter-status/index.styl

add fields into newsletter-status

---

handlers/markup/blocks/newsletter-template/index.jade
handlers/markup/blocks/newsletter-template/index.styl

fix newsletter-template button
